language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
      script:
        - sudo /bin/sh ./build_mac.sh
        - mkdir proj_release
        - cd proj_release
        - cmake -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
        - cd ..
        - mkdir proj_debug
        - cd proj_debug
        - cmake -DCMAKE_BUILD_TYPE=Debug DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
         apt:
           sources:
            - ubuntu-toolchain-r-test
           packages:
            - g++-7
      before_install:
        - eval "${MATRIX_EVAL}" 
      script:
        - sudo /bin/sh ./build_linux.sh
        - mkdir proj_release
        - cd proj_release
        - cmake -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
        - cd ..
        - mkdir proj_debug
        - cd proj_debug
        - cmake -DCMAKE_BUILD_TYPE=Debug DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
    - os: windows
      addons:
        apt:
            packages:
                - libunwind8
      env:
        global:
            # Replace framework with core when you want to build a .NET Core project, not a .NET Framework project.
            - "TRAVIS_MSBUILD_MODE=framework"
            # The location of travis-msbuild. You probably need to change this for your project!
            - "TRAVIS_MSBUILD=$TRAVIS_BUILD_DIR"
            # - "TRAVIS_MSBUILD=$TRAVIS_BUILD_DIR/travis-msbuild"
            - "TRAVIS_MSBUILD_BIN=$TRAVIS_MSBUILD/bin"
            # Replace the following path with the path to a copy of the .NET Framework you're depending on, f.e. a pre-built copy of the Mono Framework API.
            - "TRAVIS_MSBUILD_FRAMEWORK=$TRAVIS_MSBUILD/lib-dotnet"
            - "PATH=$PATH:$TRAVIS_MSBUILD_BIN"
      install:
        - if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
            export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
            export CMAKE_GENERATOR="Visual Studio 15 2017";
          fi

      script:
       - ./build_win.ps1
       - mkdir proj_release
       - cd proj_release
       - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -G "${CMAKE_GENERATOR}" ..
       - dir
       - msbuild SORT.sln