language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
      script:
       - sudo /bin/sh ./build_mac.sh
       - mkdir _out
       - cd _out
       - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
         apt:
           sources:
            - ubuntu-toolchain-r-test
           packages:
            - g++-7
      before_install:
        - eval "${MATRIX_EVAL}" 
      script:
        - sudo /bin/sh ./build_linux.sh
        - mkdir _out
        - cd _out
        - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make
    - os: windows
      script:
       - ./build_win.ps1
       - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make
