language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
      script:
       - sudo /bin/sh ./build_mac.sh
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
         apt:
           sources:
            - ubuntu-toolchain-r-test
           packages:
            - g++-7
      before_install:
        - eval "${MATRIX_EVAL}" 
      script:
       - sudo /bin/sh ./getdep_linux.sh
    - os: windows
      script:
       - ./build_win.ps1
