language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: osx
      compiler: clang
      script:
        - sudo /bin/sh ./build_mac.sh
        - mkdir proj_release
        - cd proj_release
        - cmake -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
        - cd ..
        - mkdir proj_debug
        - cd proj_debug
        - cmake -DCMAKE_BUILD_TYPE=Debug DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
         apt:
           sources:
            - ubuntu-toolchain-r-test
           packages:
            - g++-7
      before_install:
        - eval "${MATRIX_EVAL}" 
      script:
        - sudo /bin/sh ./build_linux.sh
        - mkdir proj_release
        - cd proj_release
        - cmake -DCMAKE_BUILD_TYPE=Release DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
        - cd ..
        - mkdir proj_debug
        - cd proj_debug
        - cmake -DCMAKE_BUILD_TYPE=Debug DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER .. && make -j4
    - os: windows
      script:
       - mkdir dependencies
       - wget http://45.63.123.194/sort_dependencies/win/easy_profiler.zip -O easy_profiler.zip
       - Expand-Archive .\easy_profiler.zip -DestinationPath .\dependencies\
       - mkdir _out
       - cd _out
       - cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
